sudo: required
dist: trusty
language: ruby
services:
  - postgresql
script: xvfb-run bundle exec rspec
addons:
  apt:
    sources:
#      - ubuntu-sdk-team
    packages:
      - libqtwebkit-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-tools
      - gstreamer1.0-x
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
